name: App 1 - Pack

on:
  workflow_dispatch:

jobs:  
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/cache@v3
      id: modules-cache
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install Dependencies
      if: steps.modules-cache.outputs.cache-hit != 'true'
      run: npm ci
    - run: npx nx run app-1:build
    - name: Add version to commit
      uses: actions/github-script@v6
      with:
        script: |
          await github.rest.checks.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            name: 'app-1-version',
            head_sha: context.ref,
            status: 'completed',
            conclusion: 'success',
            output: { title: '${{ github.head_ref || github.ref_name }}.${{ github.run_number }}', summary: '${{ github.head_ref || github.ref_name }}.${{ github.run_number }}', description: '${{ github.head_ref || github.ref_name }}.${{ github.run_number }}' },
            actions: [
              { label: 'Deploy to qa-svc', identifier: 'miro:deploy', description: 'Deploy to qa-svc' }
            ]
          });