name: App 1 - Pack

on:
  workflow_dispatch:

jobs:  
  app-1-version:
    runs-on: ubuntu-latest
    steps:
    - id: generate-version
      run:  |
        echo "version=${{ github.head_ref || github.ref_name }}.${{ github.run_number }}" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: [ "app-1-version" ]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/cache@v3
      id: modules-cache
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
    - run: npx nx run app-1:build
