name: App 1 - Pack

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:  
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/cache@v3
      id: modules-cache
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}    
    - run: npx nx run app-1:build
