name: App 1 - CI

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      envPAT:
        required: true

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
    - run: echo 'app-1 run'