name: K8S app-1 pack

on:
  workflow_dispatch:

jobs:
  generate-version:
    runs-on: ubuntu-latest
    steps:
    - run: echo "version ${{ github.head_ref || github.ref_name }}.${{ github.run_number }}"
  tag-commit-with-version:
    runs-on: ubuntu-latest
    name: Tagging commit with version ${{ github.head_ref || github.ref_name }}.${{ github.run_number }}
    needs: [generate-version]
    steps:
    - run: echo "tagging version"
  build-image-qa-svc:
    runs-on: ubuntu-latest
    needs: [tag-commit-with-version]
    name: Build Image k8s-app-1-qa-svc@${{ github.head_ref || github.ref_name }}.${{ github.run_number }}
    steps:
    - run: echo "Image built"
  deploy-qa-svc:
    needs: [build-image-qa-svc]
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/k8s-app-1-deploy.yml
    secrets: inherit
    with:
      environment: 'qa-svc'
  build-image-perf-1:
    runs-on: ubuntu-latest
    needs: [tag-commit-with-version]
    name: Build Image k8s-app-1-perf-1@${{ github.head_ref || github.ref_name }}.${{ github.run_number }}
    steps:
    - run: echo "Image built"
  deploy-perf-1:
    needs: [build-image-perf-1]
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/k8s-app-1-deploy.yml
    secrets: inherit
    with:
      environment: 'perf-1'
  build-image-production:
    runs-on: ubuntu-latest
    needs: [tag-commit-with-version]
    name: Build Image k8s-app-1-perf-1@${{ github.head_ref || github.ref_name }}.${{ github.run_number }}
    steps:
    - run: echo "Image built"

