name: K8S app-1 pack

on:
  workflow_dispatch:

jobs:
  generate-version:
    runs-on: ubuntu-latest
    steps:
    - run: echo "version ${{ github.head_ref || github.ref_name }}.${{ github.run_number }}"
  tag-commit-with-version:
    runs-on: ubuntu-latest
    name: Tagging commit with version ${{ github.head_ref || github.ref_name }}.${{ github.run_number }}
    needs: [generate-version]
    steps:
    - run: echo "tagging versoin"
  build-image:
    runs-on: ubuntu-latest
    needs: [tag-commit-with-version]
    strategy:
      matrix:
        environment: [qa-svc, perf-1, production]
      fail-fast: true
    name: Build Image k8s-app-1-${{ matrix.environment }}@${{ github.head_ref || github.ref_name }}.${{ github.run_number }}
    steps:
    - run: echo "Image built"
