name: Monorepo Validation

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
    - run: echo "all the work to install dependencies"
  validate-checks-all:
    runs-on: ubuntu-latest
    needs: [install-dependencies]
    strategy:
      matrix:
        command: [Lint, Check Types, Sonar]
      fail-fast: true
    name: ${{ matrix.command }}
    steps:
    - run: echo "${{ matrix.command }}"
  list-affected:
    runs-on: ubuntu-latest
    needs: [install-dependencies]
    strategy:
      matrix:
        command: [Lint, Check Types, Sonar]
      fail-fast: true
    name: List affected
    steps:
    - run: echo "List affected"
  test-affected:
    runs-on: ubuntu-latest
    needs: [install-dependencies]
    strategy:
      matrix:
        project: [k8s-app-1, static-app-1]
      fail-fast: true
    name: Unit Test ${{ matrix.project }} 
    steps:
    - run: echo "testing affected"
  trigger-affected:
    runs-on: ubuntu-latest
    needs: [validate-checks-all, list-affected, test-affected]
    strategy:
      matrix:
        project: [k8s-app-1, static-app-1]
      fail-fast: true
    name: Triggering ${{ matrix.project }} pack workflow
    steps:
    - name: Trigger via octokit
      uses: actions/github-script@v6
      with:
        script: |
          try {
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: `${{ matrix.project }}-pack.yml`,
              ref: context.ref
            });
          } catch {
          }
